# Generated by Django 3.0.4 on 2020-04-07 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_name', models.CharField(max_length=20)),
                ('year', models.IntegerField(default=1)),
                ('capacity', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_warden', models.BooleanField(default=False)),
                ('year', models.IntegerField(null=True)),
                ('is_registered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=25)),
                ('phone_no', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('pincode', models.IntegerField()),
                ('branch', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2)),
                ('mess_fee', models.CharField(max_length=20)),
                ('academic_fee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roommate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accept', models.BooleanField(default=False)),
                ('student_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student1', to='eHostelApp.Student')),
                ('student_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student2', to='eHostelApp.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.IntegerField()),
                ('h_name', models.CharField(max_length=100)),
                ('student_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eHostelApp.Student')),
                ('student_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='eHostelApp.Student')),
            ],
        ),
    ]
